//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace VoiceGrocery.Win8Store.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopList", Namespace="http://tempuri.org/")]
    public partial class ShopList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<VoiceGrocery.Win8Store.ServiceReference1.ShopItem> ShopItemsField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<VoiceGrocery.Win8Store.ServiceReference1.ShopItem> ShopItems {
            get {
                return this.ShopItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopItemsField, value) != true)) {
                    this.ShopItemsField = value;
                    this.RaisePropertyChanged("ShopItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopItem", Namespace="http://tempuri.org/")]
    public partial class ShopItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private decimal PriceField;
        
        private char ValuteField;
        
        private bool IsBoughtField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char Valute {
            get {
                return this.ValuteField;
            }
            set {
                if ((this.ValuteField.Equals(value) != true)) {
                    this.ValuteField = value;
                    this.RaisePropertyChanged("Valute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IsBought {
            get {
                return this.IsBoughtField;
            }
            set {
                if ((this.IsBoughtField.Equals(value) != true)) {
                    this.IsBoughtField = value;
                    this.RaisePropertyChanged("IsBought");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.GroceryServiceSoap")]
    public interface GroceryServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<VoiceGrocery.Win8Store.ServiceReference1.GetVersionResponse> GetVersionAsync(VoiceGrocery.Win8Store.ServiceReference1.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<VoiceGrocery.Win8Store.ServiceReference1.UploadVersionResponse> UploadVersionAsync(VoiceGrocery.Win8Store.ServiceReference1.UploadVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://tempuri.org/", Order=0)]
        public VoiceGrocery.Win8Store.ServiceReference1.GetVersionRequestBody Body;
        
        public GetVersionRequest() {
        }
        
        public GetVersionRequest(VoiceGrocery.Win8Store.ServiceReference1.GetVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionRequestBody {
        
        public GetVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public VoiceGrocery.Win8Store.ServiceReference1.GetVersionResponseBody Body;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(VoiceGrocery.Win8Store.ServiceReference1.GetVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VoiceGrocery.Win8Store.ServiceReference1.ShopList GetVersionResult;
        
        public GetVersionResponseBody() {
        }
        
        public GetVersionResponseBody(VoiceGrocery.Win8Store.ServiceReference1.ShopList GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadVersion", Namespace="http://tempuri.org/", Order=0)]
        public VoiceGrocery.Win8Store.ServiceReference1.UploadVersionRequestBody Body;
        
        public UploadVersionRequest() {
        }
        
        public UploadVersionRequest(VoiceGrocery.Win8Store.ServiceReference1.UploadVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VoiceGrocery.Win8Store.ServiceReference1.ShopList request;
        
        public UploadVersionRequestBody() {
        }
        
        public UploadVersionRequestBody(VoiceGrocery.Win8Store.ServiceReference1.ShopList request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public VoiceGrocery.Win8Store.ServiceReference1.UploadVersionResponseBody Body;
        
        public UploadVersionResponse() {
        }
        
        public UploadVersionResponse(VoiceGrocery.Win8Store.ServiceReference1.UploadVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UploadVersionResponseBody {
        
        public UploadVersionResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GroceryServiceSoapChannel : VoiceGrocery.Win8Store.ServiceReference1.GroceryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroceryServiceSoapClient : System.ServiceModel.ClientBase<VoiceGrocery.Win8Store.ServiceReference1.GroceryServiceSoap>, VoiceGrocery.Win8Store.ServiceReference1.GroceryServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GroceryServiceSoapClient() : 
                base(GroceryServiceSoapClient.GetDefaultBinding(), GroceryServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.GroceryServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GroceryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(GroceryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), GroceryServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GroceryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GroceryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GroceryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GroceryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GroceryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VoiceGrocery.Win8Store.ServiceReference1.GetVersionResponse> VoiceGrocery.Win8Store.ServiceReference1.GroceryServiceSoap.GetVersionAsync(VoiceGrocery.Win8Store.ServiceReference1.GetVersionRequest request) {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<VoiceGrocery.Win8Store.ServiceReference1.GetVersionResponse> GetVersionAsync() {
            VoiceGrocery.Win8Store.ServiceReference1.GetVersionRequest inValue = new VoiceGrocery.Win8Store.ServiceReference1.GetVersionRequest();
            inValue.Body = new VoiceGrocery.Win8Store.ServiceReference1.GetVersionRequestBody();
            return ((VoiceGrocery.Win8Store.ServiceReference1.GroceryServiceSoap)(this)).GetVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VoiceGrocery.Win8Store.ServiceReference1.UploadVersionResponse> VoiceGrocery.Win8Store.ServiceReference1.GroceryServiceSoap.UploadVersionAsync(VoiceGrocery.Win8Store.ServiceReference1.UploadVersionRequest request) {
            return base.Channel.UploadVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<VoiceGrocery.Win8Store.ServiceReference1.UploadVersionResponse> UploadVersionAsync(VoiceGrocery.Win8Store.ServiceReference1.ShopList request) {
            VoiceGrocery.Win8Store.ServiceReference1.UploadVersionRequest inValue = new VoiceGrocery.Win8Store.ServiceReference1.UploadVersionRequest();
            inValue.Body = new VoiceGrocery.Win8Store.ServiceReference1.UploadVersionRequestBody();
            inValue.Body.request = request;
            return ((VoiceGrocery.Win8Store.ServiceReference1.GroceryServiceSoap)(this)).UploadVersionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.GroceryServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.GroceryServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://voicegrocery.akhmed.ru/GroceryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return GroceryServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.GroceryServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return GroceryServiceSoapClient.GetEndpointAddress(EndpointConfiguration.GroceryServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            GroceryServiceSoap,
        }
    }
}
