//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace VoiceGrocery.WP7.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopList", Namespace="http://tempuri.org/")]
    public partial class ShopList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<VoiceGrocery.WP7.ServiceReference1.ShopItem> ShopItemsField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<VoiceGrocery.WP7.ServiceReference1.ShopItem> ShopItems {
            get {
                return this.ShopItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopItemsField, value) != true)) {
                    this.ShopItemsField = value;
                    this.RaisePropertyChanged("ShopItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopItem", Namespace="http://tempuri.org/")]
    public partial class ShopItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private decimal PriceField;
        
        private char ValuteField;
        
        private bool IsBoughtField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char Valute {
            get {
                return this.ValuteField;
            }
            set {
                if ((this.ValuteField.Equals(value) != true)) {
                    this.ValuteField = value;
                    this.RaisePropertyChanged("Valute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IsBought {
            get {
                return this.IsBoughtField;
            }
            set {
                if ((this.IsBoughtField.Equals(value) != true)) {
                    this.IsBoughtField = value;
                    this.RaisePropertyChanged("IsBought");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.GroceryServiceSoap")]
    public interface GroceryServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetVersion", ReplyAction="*")]
        System.IAsyncResult BeginGetVersion(VoiceGrocery.WP7.ServiceReference1.GetVersionRequest request, System.AsyncCallback callback, object asyncState);
        
        VoiceGrocery.WP7.ServiceReference1.GetVersionResponse EndGetVersion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UploadVersion", ReplyAction="*")]
        System.IAsyncResult BeginUploadVersion(VoiceGrocery.WP7.ServiceReference1.UploadVersionRequest request, System.AsyncCallback callback, object asyncState);
        
        VoiceGrocery.WP7.ServiceReference1.UploadVersionResponse EndUploadVersion(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://tempuri.org/", Order=0)]
        public VoiceGrocery.WP7.ServiceReference1.GetVersionRequestBody Body;
        
        public GetVersionRequest() {
        }
        
        public GetVersionRequest(VoiceGrocery.WP7.ServiceReference1.GetVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionRequestBody {
        
        public GetVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public VoiceGrocery.WP7.ServiceReference1.GetVersionResponseBody Body;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(VoiceGrocery.WP7.ServiceReference1.GetVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VoiceGrocery.WP7.ServiceReference1.ShopList GetVersionResult;
        
        public GetVersionResponseBody() {
        }
        
        public GetVersionResponseBody(VoiceGrocery.WP7.ServiceReference1.ShopList GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadVersion", Namespace="http://tempuri.org/", Order=0)]
        public VoiceGrocery.WP7.ServiceReference1.UploadVersionRequestBody Body;
        
        public UploadVersionRequest() {
        }
        
        public UploadVersionRequest(VoiceGrocery.WP7.ServiceReference1.UploadVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VoiceGrocery.WP7.ServiceReference1.ShopList request;
        
        public UploadVersionRequestBody() {
        }
        
        public UploadVersionRequestBody(VoiceGrocery.WP7.ServiceReference1.ShopList request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public VoiceGrocery.WP7.ServiceReference1.UploadVersionResponseBody Body;
        
        public UploadVersionResponse() {
        }
        
        public UploadVersionResponse(VoiceGrocery.WP7.ServiceReference1.UploadVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UploadVersionResponseBody {
        
        public UploadVersionResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GroceryServiceSoapChannel : VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VoiceGrocery.WP7.ServiceReference1.ShopList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VoiceGrocery.WP7.ServiceReference1.ShopList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroceryServiceSoapClient : System.ServiceModel.ClientBase<VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap>, VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap {
        
        private BeginOperationDelegate onBeginGetVersionDelegate;
        
        private EndOperationDelegate onEndGetVersionDelegate;
        
        private System.Threading.SendOrPostCallback onGetVersionCompletedDelegate;
        
        private BeginOperationDelegate onBeginUploadVersionDelegate;
        
        private EndOperationDelegate onEndUploadVersionDelegate;
        
        private System.Threading.SendOrPostCallback onUploadVersionCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public GroceryServiceSoapClient() {
        }
        
        public GroceryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroceryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroceryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroceryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetVersionCompletedEventArgs> GetVersionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UploadVersionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap.BeginGetVersion(VoiceGrocery.WP7.ServiceReference1.GetVersionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetVersion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetVersion(System.AsyncCallback callback, object asyncState) {
            VoiceGrocery.WP7.ServiceReference1.GetVersionRequest inValue = new VoiceGrocery.WP7.ServiceReference1.GetVersionRequest();
            inValue.Body = new VoiceGrocery.WP7.ServiceReference1.GetVersionRequestBody();
            return ((VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap)(this)).BeginGetVersion(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VoiceGrocery.WP7.ServiceReference1.GetVersionResponse VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap.EndGetVersion(System.IAsyncResult result) {
            return base.Channel.EndGetVersion(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private VoiceGrocery.WP7.ServiceReference1.ShopList EndGetVersion(System.IAsyncResult result) {
            VoiceGrocery.WP7.ServiceReference1.GetVersionResponse retVal = ((VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap)(this)).EndGetVersion(result);
            return retVal.Body.GetVersionResult;
        }
        
        private System.IAsyncResult OnBeginGetVersion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetVersion(callback, asyncState);
        }
        
        private object[] OnEndGetVersion(System.IAsyncResult result) {
            VoiceGrocery.WP7.ServiceReference1.ShopList retVal = this.EndGetVersion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetVersionCompleted(object state) {
            if ((this.GetVersionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetVersionCompleted(this, new GetVersionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetVersionAsync() {
            this.GetVersionAsync(null);
        }
        
        public void GetVersionAsync(object userState) {
            if ((this.onBeginGetVersionDelegate == null)) {
                this.onBeginGetVersionDelegate = new BeginOperationDelegate(this.OnBeginGetVersion);
            }
            if ((this.onEndGetVersionDelegate == null)) {
                this.onEndGetVersionDelegate = new EndOperationDelegate(this.OnEndGetVersion);
            }
            if ((this.onGetVersionCompletedDelegate == null)) {
                this.onGetVersionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetVersionCompleted);
            }
            base.InvokeAsync(this.onBeginGetVersionDelegate, null, this.onEndGetVersionDelegate, this.onGetVersionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap.BeginUploadVersion(VoiceGrocery.WP7.ServiceReference1.UploadVersionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUploadVersion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUploadVersion(VoiceGrocery.WP7.ServiceReference1.ShopList request, System.AsyncCallback callback, object asyncState) {
            VoiceGrocery.WP7.ServiceReference1.UploadVersionRequest inValue = new VoiceGrocery.WP7.ServiceReference1.UploadVersionRequest();
            inValue.Body = new VoiceGrocery.WP7.ServiceReference1.UploadVersionRequestBody();
            inValue.Body.request = request;
            return ((VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap)(this)).BeginUploadVersion(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VoiceGrocery.WP7.ServiceReference1.UploadVersionResponse VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap.EndUploadVersion(System.IAsyncResult result) {
            return base.Channel.EndUploadVersion(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndUploadVersion(System.IAsyncResult result) {
            VoiceGrocery.WP7.ServiceReference1.UploadVersionResponse retVal = ((VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap)(this)).EndUploadVersion(result);
        }
        
        private System.IAsyncResult OnBeginUploadVersion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VoiceGrocery.WP7.ServiceReference1.ShopList request = ((VoiceGrocery.WP7.ServiceReference1.ShopList)(inValues[0]));
            return this.BeginUploadVersion(request, callback, asyncState);
        }
        
        private object[] OnEndUploadVersion(System.IAsyncResult result) {
            this.EndUploadVersion(result);
            return null;
        }
        
        private void OnUploadVersionCompleted(object state) {
            if ((this.UploadVersionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UploadVersionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UploadVersionAsync(VoiceGrocery.WP7.ServiceReference1.ShopList request) {
            this.UploadVersionAsync(request, null);
        }
        
        public void UploadVersionAsync(VoiceGrocery.WP7.ServiceReference1.ShopList request, object userState) {
            if ((this.onBeginUploadVersionDelegate == null)) {
                this.onBeginUploadVersionDelegate = new BeginOperationDelegate(this.OnBeginUploadVersion);
            }
            if ((this.onEndUploadVersionDelegate == null)) {
                this.onEndUploadVersionDelegate = new EndOperationDelegate(this.OnEndUploadVersion);
            }
            if ((this.onUploadVersionCompletedDelegate == null)) {
                this.onUploadVersionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadVersionCompleted);
            }
            base.InvokeAsync(this.onBeginUploadVersionDelegate, new object[] {
                        request}, this.onEndUploadVersionDelegate, this.onUploadVersionCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap CreateChannel() {
            return new GroceryServiceSoapClientChannel(this);
        }
        
        private class GroceryServiceSoapClientChannel : ChannelBase<VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap>, VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap {
            
            public GroceryServiceSoapClientChannel(System.ServiceModel.ClientBase<VoiceGrocery.WP7.ServiceReference1.GroceryServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetVersion(VoiceGrocery.WP7.ServiceReference1.GetVersionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetVersion", _args, callback, asyncState);
                return _result;
            }
            
            public VoiceGrocery.WP7.ServiceReference1.GetVersionResponse EndGetVersion(System.IAsyncResult result) {
                object[] _args = new object[0];
                VoiceGrocery.WP7.ServiceReference1.GetVersionResponse _result = ((VoiceGrocery.WP7.ServiceReference1.GetVersionResponse)(base.EndInvoke("GetVersion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUploadVersion(VoiceGrocery.WP7.ServiceReference1.UploadVersionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UploadVersion", _args, callback, asyncState);
                return _result;
            }
            
            public VoiceGrocery.WP7.ServiceReference1.UploadVersionResponse EndUploadVersion(System.IAsyncResult result) {
                object[] _args = new object[0];
                VoiceGrocery.WP7.ServiceReference1.UploadVersionResponse _result = ((VoiceGrocery.WP7.ServiceReference1.UploadVersionResponse)(base.EndInvoke("UploadVersion", _args, result)));
                return _result;
            }
        }
    }
}
